2023-04-01 08:27:51,792 : INFO : root : Loading config.
2023-04-01 08:27:52,186 : INFO : ConfigProcessor : Config spec file cache created: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/config_spec.mpf_cache
2023-04-01 08:27:52,186 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2023-04-01 08:27:52,186 : WARNING : ConfigProcessor : Config file in cache changed: /Users/tpetch/Documents/trashland_3/config/config.yaml
2023-04-01 08:27:52,186 : INFO : ConfigProcessor : Loading config from file /Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/mpfconfig.yaml.
2023-04-01 08:27:52,258 : INFO : ConfigProcessor : Loading config: /Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/mpfconfig.yaml
2023-04-01 08:27:52,258 : INFO : ConfigProcessor : Loading config from file /Users/tpetch/Documents/trashland_3/config/config.yaml.
2023-04-01 08:27:52,393 : INFO : ConfigProcessor : Loading config: /Users/tpetch/Documents/trashland_3/config/config.yaml
2023-04-01 08:27:52,395 : INFO : ConfigProcessor : Config file cache created: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/28c67afebeedf0bcd540f5dc9898a885.mpf_cache
2023-04-01 08:27:52,432 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/03cea1619b79a61f4f0eef3c59cdaa46.mpf_cache
2023-04-01 08:27:52,432 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/d3948d842c6309f14ab557c3c72320d0.mpf_cache
2023-04-01 08:27:52,433 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/af594ef60d8c7d8001f2f983e2ab9758.mpf_cache
2023-04-01 08:27:52,434 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/e2af7416374ff81cc755b6fa72ebf9da.mpf_cache
2023-04-01 08:27:52,436 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/a37a2141962f60258a07880b3484644a.mpf_cache
2023-04-01 08:27:52,437 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/fe6633bcfbf8321353ee11210ab6caf6.mpf_cache
2023-04-01 08:27:52,437 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/1e3c425cd39fabe39b839fb5c1f9b184.mpf_cache
2023-04-01 08:27:52,440 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/5e7e7afe019ac2096dd50ba3141e047f.mpf_cache
2023-04-01 08:27:52,440 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/0c011456348cc487d2bd3b88b4038334.mpf_cache
2023-04-01 08:27:52,441 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/bea7ec732b9b9f1ccc3e63c697825f10.mpf_cache
2023-04-01 08:27:52,442 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/e91719688063f997df3fd4e51c395a8b.mpf_cache
2023-04-01 08:27:52,444 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/e42a2b79ff3d1dd1cfe9b0905c00e5e1.mpf_cache
2023-04-01 08:27:52,444 : INFO : Machine : Mission Pinball Framework Core Engine v0.56.1.dev4
2023-04-01 08:27:52,444 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2023-04-01-08-27-51-mpf-Tanners-MacBook-Pro-2.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2023-04-01 08:27:52,444 : INFO : Machine : MPF path: /Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf
2023-04-01 08:27:52,444 : INFO : Machine : Machine path: /Users/tpetch/Documents/trashland_3
2023-04-01 08:27:52,445 : INFO : Machine : Platform: darwin
2023-04-01 08:27:52,445 : INFO : Machine : Python executable location: /Users/tpetch/.local/pipx/venvs/mpf/bin/python
2023-04-01 08:27:52,445 : INFO : Machine : Python version: 3.9.13 (64-bit)
2023-04-01 08:27:52,450 : INFO : Machine : Initialise MPF.
2023-04-01 08:27:52,501 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2023-04-01 08:27:52,526 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2023-04-01 08:27:52,526 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.56.1.dev4', 'prev_value': None, 'change': True}
2023-04-01 08:27:52,526 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.56.1.dev4, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2023-04-01 08:27:52,526 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2023-04-01 08:27:52,537 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-10.16-x86_64-i386-64bit', 'prev_value': None, 'change': True}
2023-04-01 08:27:52,537 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2023-04-01 08:27:52,537 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '22.2.0', 'prev_value': None, 'change': True}
2023-04-01 08:27:52,537 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64', 'prev_value': None, 'change': True}
2023-04-01 08:27:52,537 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2023-04-01 08:27:52,537 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2023-04-01 08:27:52,596 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2023-04-01 08:27:52,602 : INFO : ball_device.bd_vuk_back : BCH: Initial count: 0
2023-04-01 08:27:52,602 : INFO : ball_device.bd_vuk_back : State: idle
2023-04-01 08:27:52,602 : INFO : ball_device.bd_vuk_right : BCH: Initial count: 0
2023-04-01 08:27:52,603 : INFO : ball_device.bd_vuk_right : State: idle
2023-04-01 08:27:52,603 : INFO : ball_device.bd_vuk_bot : BCH: Initial count: 0
2023-04-01 08:27:52,603 : INFO : ball_device.bd_vuk_bot : State: idle
2023-04-01 08:27:52,604 : INFO : ball_device.bd_trough : BCH: Initial count: 0
2023-04-01 08:27:52,604 : INFO : ball_device.bd_trough : State: idle
2023-04-01 08:27:52,604 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2023-04-01 08:27:52,605 : INFO : ball_device.bd_plunger : State: idle
2023-04-01 08:27:52,621 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2023-04-01 08:27:52,624 : ERROR : asyncio : Exception in callback <bound method EventManager._queue_task_done of <mpf.core.events.EventManager object at 0x7fc7f7a2a9a0>>
handle: <Handle EventManager._queue_task_done>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/events.py", line 744, in _queue_task_done
    future.result()
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/events.py", line 657, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/show_controller.py", line 52, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/assets/show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/assets/show.py", line 201, in _process_step_actions
    raise e
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/assets/show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/config_players/device_config_player.py", line 56, in validate_config_entry
    raise e
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/config_players/device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/config_players/device_config_player.py", line 86, in _validate_config_item
    devices = self._expand_device(device)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/config_players/device_config_player.py", line 115, in _expand_device
    return self.raise_config_error(
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "tl2-ch-color-wheel-cw-2sec-Set" >> Failed to load config player tl2-ch-color-wheel-cw-2sec-Set:lights with settings {'l_character_1_big': '7F0000', 'l_character_1_mode1': '7F0000', 'l_character_1_mode2': '804014', 'l_character_1_small1': '7F0100', 'l_character_1_small2': '804014', 'l_character_1_small3': '804014', 'l_character_2_big': '4E2A76', 'l_character_2_mode1': '7A0566', 'l_character_2_mode2': '7A0666', 'l_character_2_small1': '4E2A76', 'l_character_2_small2': '4E2A76', 'l_character_2_small3': '4E2A76', 'l_character_3_big': '000080', 'l_character_3_mode1': '000080', 'l_character_3_mode2': '005174', 'l_character_3_small1': '005174', 'l_character_3_small2': '005174', 'l_character_3_small3': '005174', 'l_character_4_big': '797702', 'l_character_4_mode1': '807900', 'l_character_4_mode2': '807900', 'l_character_4_small1': '115926', 'l_character_4_small2': '115926', 'l_character_4_small3': '807900'} >> Could not find a lights device with name or tag l_character_1_big, from list ['l_character_1_big'] Error Code: CFE-light_player-101 (https://docs.missionpinball.org/en/dev/logs/CFE-light_player-101.html)
2023-04-01 08:27:52,629 : INFO : Machine : Starting the main run loop.
2023-04-01 08:27:52,629 : INFO : Machine : Shutting down...
2023-04-01 08:27:52,630 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2023-04-01 08:27:53,633 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/machine.py", line 797, in _run_loop
    raise self._exception['exception']
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/events.py", line 744, in _queue_task_done
    future.result()
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/events.py", line 657, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/show_controller.py", line 52, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/assets/show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/assets/show.py", line 201, in _process_step_actions
    raise e
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/assets/show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/config_players/device_config_player.py", line 56, in validate_config_entry
    raise e
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/config_players/device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/config_players/device_config_player.py", line 86, in _validate_config_item
    devices = self._expand_device(device)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/config_players/device_config_player.py", line 115, in _expand_device
    return self.raise_config_error(
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "tl2-ch-color-wheel-cw-2sec-Set" >> Failed to load config player tl2-ch-color-wheel-cw-2sec-Set:lights with settings {'l_character_1_big': '7F0000', 'l_character_1_mode1': '7F0000', 'l_character_1_mode2': '804014', 'l_character_1_small1': '7F0100', 'l_character_1_small2': '804014', 'l_character_1_small3': '804014', 'l_character_2_big': '4E2A76', 'l_character_2_mode1': '7A0566', 'l_character_2_mode2': '7A0666', 'l_character_2_small1': '4E2A76', 'l_character_2_small2': '4E2A76', 'l_character_2_small3': '4E2A76', 'l_character_3_big': '000080', 'l_character_3_mode1': '000080', 'l_character_3_mode2': '005174', 'l_character_3_small1': '005174', 'l_character_3_small2': '005174', 'l_character_3_small3': '005174', 'l_character_4_big': '797702', 'l_character_4_mode1': '807900', 'l_character_4_mode2': '807900', 'l_character_4_small1': '115926', 'l_character_4_small2': '115926', 'l_character_4_small3': '807900'} >> Could not find a lights device with name or tag l_character_1_big, from list ['l_character_1_big'] Error Code: CFE-light_player-101 (https://docs.missionpinball.org/en/dev/logs/CFE-light_player-101.html)
2023-04-01 08:28:43,137 : INFO : root : MPF run loop ended.
