2023-04-01 14:34:53,559 : INFO : root : Loading config.
2023-04-01 14:34:53,959 : INFO : ConfigProcessor : Config spec file cache created: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/config_spec.mpf_cache
2023-04-01 14:34:53,960 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2023-04-01 14:34:53,960 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/28c67afebeedf0bcd540f5dc9898a885.mpf_cache
2023-04-01 14:34:54,038 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/03cea1619b79a61f4f0eef3c59cdaa46.mpf_cache
2023-04-01 14:34:54,039 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/d3948d842c6309f14ab557c3c72320d0.mpf_cache
2023-04-01 14:34:54,040 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/03cea1619b79a61f4f0eef3c59cdaa46.mpf_cache
2023-04-01 14:34:54,040 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/e2b5fc2c1600bc34f2e7c001687491b8.mpf_cache
2023-04-01 14:34:54,041 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/cffaccb26f43f88b68b4b64e86367a3c.mpf_cache
2023-04-01 14:34:54,042 : INFO : ConfigProcessor : Loading config from file /Users/tpetch/Documents/trashland_3/modes/start_ball_save/config/start_ball_save.yaml.
2023-04-01 14:34:54,046 : INFO : ConfigProcessor : Loading config: /Users/tpetch/Documents/trashland_3/modes/start_ball_save/config/start_ball_save.yaml
2023-04-01 14:34:54,046 : INFO : ConfigProcessor : Config file cache created: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/1a491952b1b86d65aa143eb7204b9608.mpf_cache
2023-04-01 14:34:54,047 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/a37a2141962f60258a07880b3484644a.mpf_cache
2023-04-01 14:34:54,048 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/1abbb484e5c2eb8b7dba517683fc6f83.mpf_cache
2023-04-01 14:34:54,050 : INFO : Machine : Mission Pinball Framework Core Engine v0.56.1.dev4
2023-04-01 14:34:54,050 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2023-04-01-14-34-53-mpf-Tanners-MacBook-Pro-2.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2023-04-01 14:34:54,050 : INFO : Machine : MPF path: /Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf
2023-04-01 14:34:54,050 : INFO : Machine : Machine path: /Users/tpetch/Documents/trashland_3
2023-04-01 14:34:54,050 : INFO : Machine : Platform: darwin
2023-04-01 14:34:54,050 : INFO : Machine : Python executable location: /Users/tpetch/.local/pipx/venvs/mpf/bin/python
2023-04-01 14:34:54,050 : INFO : Machine : Python version: 3.9.13 (64-bit)
2023-04-01 14:34:54,066 : INFO : Machine : Initialise MPF.
2023-04-01 14:34:54,169 : INFO : [NET] : Trying to connect to /dev/tty.usbmodem141401 at 921600bps
2023-04-01 14:34:54,174 : INFO : [NET] : Connected to /dev/tty.usbmodem141401 at 921600bps
2023-04-01 14:34:54,188 : INFO : [NET] : Connected to FP-CPU-2000 with firmware v02.06
2023-04-01 14:34:54,188 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '02.06', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,188 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-2000', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,191 : INFO : [NET] : Registered I/O Board 0: Model: FP-I/O-0804, Firmware: 01.09, Switches: 8, Drivers: 4
2023-04-01 14:34:54,192 : INFO : [NET] : Registered I/O Board 1: Model: FP-I/O-0804, Firmware: 01.09, Switches: 8, Drivers: 4
2023-04-01 14:34:54,194 : INFO : [NET] : Registered I/O Board 2: Model: FP-I/O-3208, Firmware: 01.09, Switches: 32, Drivers: 8
2023-04-01 14:34:54,195 : INFO : [NET] : Registered I/O Board 3: Model: FP-I/O-1616, Firmware: 01.09, Switches: 16, Drivers: 16
2023-04-01 14:34:54,196 : INFO : [NET] : Registered I/O Board 4: Model: FP-I/O-3208, Firmware: 01.09, Switches: 32, Drivers: 8
2023-04-01 14:34:54,198 : INFO : [EXP] : Trying to connect to /dev/tty.usbmodem141403 at 921600bps
2023-04-01 14:34:54,202 : INFO : [EXP] : Connected to /dev/tty.usbmodem141403 at 921600bps
2023-04-01 14:34:54,208 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,252 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2023-04-01 14:34:54,252 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-04-01 14:34:54,252 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.56.1.dev4', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,252 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.56.1.dev4, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,253 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,269 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-10.16-x86_64-i386-64bit', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,269 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,269 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '22.2.0', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,269 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,269 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2023-04-01 14:34:54,269 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2023-04-01 14:34:54,318 : ERROR : asyncio : Exception in callback functools.partial(<function EventManager._async_handler_done at 0x7fc9c7250430>, <QueuedEvent>)
handle: <Handle functools.partial(<function EventManager._async_handler_done at 0x7fc9c7250430>, <QueuedEvent>)>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/events.py", line 121, in _async_handler_done
    future.result()
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/device_manager.py", line 90, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/mode.py", line 433, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/devices/shot.py", line 72, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 205, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 257, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 696, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 407, in _validate_type_machine
    return self.validation_error(item, validation_failure_info,
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 713, in validation_error
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry mode:lane_rotate:shots:r_left_outlane:switch = "s_left_outlane" is not valid. Device "s_left_outlane" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-6.html)
2023-04-01 14:34:54,325 : INFO : Machine : Starting the main run loop.
2023-04-01 14:34:54,327 : INFO : Machine : Shutting down...
2023-04-01 14:34:54,327 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2023-04-01 14:34:55,439 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/machine.py", line 797, in _run_loop
    raise self._exception['exception']
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/events.py", line 121, in _async_handler_done
    future.result()
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/device_manager.py", line 90, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/mode.py", line 433, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/devices/shot.py", line 72, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 205, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 257, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 696, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 407, in _validate_type_machine
    return self.validation_error(item, validation_failure_info,
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 713, in validation_error
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry mode:lane_rotate:shots:r_left_outlane:switch = "s_left_outlane" is not valid. Device "s_left_outlane" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-6.html)
2023-04-01 14:35:16,057 : INFO : root : MPF run loop ended.
