2024-04-17 22:22:39,221 : INFO : root : Loading config.
2024-04-17 22:22:39,223 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-04-17 22:22:39,223 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/871505f0f2d2915bd502f0a1fb110f3b.mpf_cache
2024-04-17 22:22:39,244 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/640347d32029b3f32c9ad31d7a1b4b81.mpf_cache
2024-04-17 22:22:39,244 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/edcc5f1d3215b377c9faab88c62e4ce0.mpf_cache
2024-04-17 22:22:39,244 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/640347d32029b3f32c9ad31d7a1b4b81.mpf_cache
2024-04-17 22:22:39,244 : WARNING : ConfigProcessor : Config file in cache changed: /Users/tannerpetch/Documents/GitHub/lofab/modes/base/config/base.yaml
2024-04-17 22:22:39,244 : INFO : ConfigProcessor : Loading config from file /Users/tannerpetch/Documents/GitHub/lofab/modes/base/config/base.yaml.
2024-04-17 22:22:39,246 : INFO : ConfigProcessor : Loading config: /Users/tannerpetch/Documents/GitHub/lofab/modes/base/config/base.yaml
2024-04-17 22:22:39,246 : INFO : ConfigProcessor : Config file cache created: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/f97c90855879603280fcc571f5c42639.mpf_cache
2024-04-17 22:22:39,246 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/1875c266911f801b691956fe9e9284d6.mpf_cache
2024-04-17 22:22:39,246 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/3dbc438e88423aa3ff742db2713b600f.mpf_cache
2024-04-17 22:22:39,247 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/91adfe62d94491e9c757b00a8e3b96af.mpf_cache
2024-04-17 22:22:39,248 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/154d071a3850556c6f3eae37bf41c8b6.mpf_cache
2024-04-17 22:22:39,248 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/ab100dbe0e16472b56f0213f3842a00f.mpf_cache
2024-04-17 22:22:39,249 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/f03ad90ccd2c053e9e5d10795d01f4ba.mpf_cache
2024-04-17 22:22:39,250 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/0f3c951d4c93079ae3fac6429c5bc2ee.mpf_cache
2024-04-17 22:22:39,250 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/8bf004783a280ac33d17b88f37848116.mpf_cache
2024-04-17 22:22:39,251 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/d5d50eaa09e055f3a827c6269a3aa165.mpf_cache
2024-04-17 22:22:39,251 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.1.dev3
2024-04-17 22:22:39,251 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-04-17-22-22-39-mpf-Tanners-Laptop.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-04-17 22:22:39,251 : INFO : Machine : MPF path: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf
2024-04-17 22:22:39,251 : INFO : Machine : Machine path: /Users/tannerpetch/Documents/GitHub/lofab
2024-04-17 22:22:39,251 : INFO : Machine : Platform: darwin
2024-04-17 22:22:39,251 : INFO : Machine : Python executable location: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
2024-04-17 22:22:39,251 : INFO : Machine : Python version: 3.9.13 (64-bit)
2024-04-17 22:22:39,252 : INFO : Machine : Initializing MPF...
2024-04-17 22:22:39,271 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-04-17 22:22:39,282 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-04-17 22:22:39,283 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-04-17 22:22:39,283 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.1.dev3', 'prev_value': None, 'change': True}
2024-04-17 22:22:39,283 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.1.dev3, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-04-17 22:22:39,283 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2024-04-17 22:22:39,289 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-14.3-arm64-arm-64bit', 'prev_value': None, 'change': True}
2024-04-17 22:22:39,289 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2024-04-17 22:22:39,289 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '23.3.0', 'prev_value': None, 'change': True}
2024-04-17 22:22:39,289 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 23.3.0: Thu Dec 21 02:29:41 PST 2023; root:xnu-10002.81.5~11/RELEASE_ARM64_T8122', 'prev_value': None, 'change': True}
2024-04-17 22:22:39,289 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'arm64', 'prev_value': None, 'change': True}
2024-04-17 22:22:39,289 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-04-17 22:22:39,302 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-04-17 22:22:39,304 : INFO : ball_device.bd_vuk : BCH: Initial count: 0
2024-04-17 22:22:39,304 : INFO : ball_device.bd_vuk : State: idle
2024-04-17 22:22:39,304 : INFO : ball_device.bd_trough : BCH: Initial count: 0
2024-04-17 22:22:39,304 : INFO : ball_device.bd_trough : State: idle
2024-04-17 22:22:39,308 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2024-04-17 22:22:39,451 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe..._1:" found.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe..._1:" found.')>)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py", line 795, in _queue_task_done
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/assets/show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/assets/show.py", line 210, in _process_step_actions
    self._show_validation_error('Invalid section "{}:" found.'.format(key), 4)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/assets/show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "flash_pop" >> Invalid section "l_pop_flasher_1:" found. Context: flash_pop Error Code: CFE-show-4 (https://missionpinball.org/logs)
2024-04-17 22:22:39,454 : INFO : Machine : Starting the main run loop.
2024-04-17 22:22:39,454 : INFO : Machine : Shutting down...
2024-04-17 22:22:39,454 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-04-17 22:22:40,456 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py", line 795, in _queue_task_done
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/assets/show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/assets/show.py", line 210, in _process_step_actions
    self._show_validation_error('Invalid section "{}:" found.'.format(key), 4)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/assets/show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "flash_pop" >> Invalid section "l_pop_flasher_1:" found. Context: flash_pop Error Code: CFE-show-4 (https://missionpinball.org/logs)
2024-04-17 22:23:58,800 : INFO : root : MPF run loop ended.
